app:
  ~chart: app
  probesPath: /healthz
  imagePackage: app
  volumes:
    - name: repos
      emptyDir: {}
  volumeMounts:
    - mountPath: /app/repos
      name: repos
  envFrom:
  - secretRef:
      name: app
  - configMapRef:
      name: app
