app:
  ~chart: app
  ~needs: [build-app]
  probesPath: /healthz
  imagePackage: app
  volumes:
    - name: repos
      emptyDir: {}
  volumeMounts:
    - mountPath: /app/repos
      name: repos
  envFrom:
  - secretRef:
      name: app
  - configMapRef:
      name: app

jobs:
  ~chart: jobs
  runs:
    build-app:
      use: build
      memoryLimit: 8Gi
      with:
        imagePackage: app
