name: Kontinuous

on:
  repository_dispatch:
    types: [pr-kontinuous]

jobs:
  yarn-cache:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: "SocialGouv/${{github.event.client_payload.repository}}"

      - name: Add Dockerfile
        if: ${{ hashFiles('Dockerfile') == '' }}
        run: |
          npx degit socialgouv/socialgouv-app/templates/default/Dockerfile Dockerfile

      - name: Add .dockerignore
        if: ${{ hashFiles('.dockerignore') == '' }}
        run: |
          npx degit socialgouv/socialgouv-app/templates/default/.dockerignore .dockerignore

      - name: Add Kontinuous config
        if: ${{ hashFiles('.kontinuous/values.yaml') == '' }}
        run: |
          npx degit socialgouv/socialgouv-app/templates/default/.kontinuous .kontinuous

      - name: Generate Github App token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          body: ${{github.event.client_payload.body}}
          title: ${{github.event.client_payload.title}}
          labels: ${{github.event.client_payload.labels}}
          branch: ${{github.event.client_payload.branch}}
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: ${{github.event.client_payload.commitMessage}}
