name: Kontinuous

on:
  repository_dispatch:
    types: [pr-kontinuous]

jobs:
  yarn-cache:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: "SocialGouv/${{github.event.client_payload.repository}}"

      - name: Add Dockerfile
        if: ${{ hashFiles('Dockerfile') == '' }}
        run: |
          npx degit socialgouv/socialgouv-app/templates/default/Dockerfile Dockerfile

      - name: Add .dockerignore
        if: ${{ hashFiles('.dockerignore') == '' }}
        run: |
          npx degit socialgouv/socialgouv-app/templates/default/.dockerignore .dockerignore

      - name: Add Kontinuous config
        if: ${{ hashFiles('.kontinuous/values.yaml') == '' }}
        run: |
          npx degit socialgouv/socialgouv-app/templates/default/.kontinuous .kontinuous

      - name: Create workflows directory
        run: mkdir -p .github/workflows

      - name: Add deactivate workflow
        if: ${{ hashFiles('.github/workflows/deactivate.yaml') == '' }}
        run: |
          npx degit socialgouv/socialgouv-app/templates/default/.github/workflows/deactivate.yaml .github/workflows/deactivate.yaml

      - name: Add preproduction workflow
        if: ${{ hashFiles('.github/workflows/preproduction.yaml') == '' }}
        run: |
          npx degit socialgouv/socialgouv-app/templates/default/.github/workflows/preproduction.yaml .github/workflows/preproduction.yaml

      - name: Add production workflow
        if: ${{ hashFiles('.github/workflows/production.yaml') == '' }}
        run: |
          npx degit socialgouv/socialgouv-app/templates/default/.github/workflows/production.yaml .github/workflows/production.yaml

      - name: Add release workflow
        if: ${{ hashFiles('.github/workflows/release.yaml') == '' }}
        run: |
          npx degit socialgouv/socialgouv-app/templates/default/.github/workflows/release.yaml .github/workflows/release.yaml

      - name: Add review-auto workflow
        if: ${{ hashFiles('.github/workflows/review-auto.yaml') == '' }}
        run: |
          npx degit socialgouv/socialgouv-app/templates/default/.github/workflows/review-auto.yaml .github/workflows/review-auto.yaml

      - name: Add review workflow
        if: ${{ hashFiles('.github/workflows/review.yaml') == '' }}
        run: |
          npx degit socialgouv/socialgouv-app/templates/default/.github/workflows/review.yaml .github/workflows/review.yaml

      - name: Generate Github App token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          body: ${{github.event.client_payload.body}}
          title: ${{github.event.client_payload.title}}
          labels: ${{github.event.client_payload.labels}}
          branch: ${{github.event.client_payload.branch}}
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: ${{github.event.client_payload.commitMessage}}
