name: Yarn Cache

on:
  repository_dispatch:
    types: [pr-yarn-berry]

jobs:
  yarn-cache:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: "SocialGouv/${{github.event.client_payload.repository}}"

      - name: Install yarn berry
        run: |
          yarn set version berry
          yarn plugin import https://codeberg.org/devthefuture/yarn-plugin-fetch/raw/branch/master/bundles/@yarnpkg/plugin-fetch.js

      - name: Update yarn
        run: |
          export YARN_ENABLE_IMMUTABLE_INSTALLS=false
          yarn install

      - name: update .gitignore
        run: |
          echo "
          # yarn berry
          .pnp.*
          .yarn/*
          !.yarn/patches
          !.yarn/plugins
          !.yarn/releases
          !.yarn/sdks
          !.yarn/versions
          " >> .gitignore

      - name: Generate Github App token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: chore/yarn-berry
          commit-message: "add yarn berry"
          title: "[SRE] Yarn Berry"
          body: |
            This pull request has been geenrated automaticaly.
            The aim of this pull request his to add `Yarn Berry` to this project.
            Installation of `Yarn Berry` is a technical recommandation of **La Fabrique Numérique** des ministères sociaux.
